(module $testModule
  (func $factorial (param $n i32) (result i32)
    (get_local 0)
    (i32.const 0)
    (i32.eq)
    (if
      (then
        (i32.const 1)
        (return)))
    (get_local 0)
    (get_local 0)
    (i32.const 1)
    (i32.sub)
    (call 0)
    (i32.mul)
    (return)
  )
  (func $fib (param $n i32) (result i32)
    (get_local 0)
    (i32.const 0)
    (i32.eq)
    (if
      (then
        (i32.const 0)
        (return)))
    (get_local 0)
    (i32.const 1)
    (i32.eq)
    (if
      (then
        (i32.const 1)
        (return)))
    (get_local 0)
    (i32.const 1)
    (i32.sub)
    (call 0)
    (get_local 0)
    (i32.const 2)
    (i32.sub)
    (call 0)
    (i32.add)
    (return)
  )
)